let movies = [

  { name: "Inception", rating: 87 },
  { name: "The Matrix", rating: 42 },
  { name: "The Godfather", rating: 99 },
  { name: "The Shawshank Redemption", rating: 81 },
  { name: "The Dark Knight", rating: 15 },
  { name: "Pulp Fiction", rating: 64 },
  { name: "The Lord of the Rings: The Return of the King", rating: 91 },
  { name: "Fight Club", rating: 58 },
  { name: "Forrest Gump", rating: 36 },
  { name: "The Empire Strikes Back", rating: 80 },
  { name: "Interstellar", rating: 23 },
  { name: "Gladiator", rating: 67 },
  { name: "Saving Private Ryan", rating: 94 },
  { name: "The Silence of the Lambs", rating: 12 },

/*
  { name: "Se7en", rating: 4 },
  { name: "The Usual Suspects", rating: 4 },
  { name: "Goodfellas", rating: 5 },
  { name: "Braveheart", rating: 4 },
  { name: "Titanic", rating: 4 },
  { name: "Avatar", rating: 3 },
  { name: "Avengers: Endgame", rating: 4 },
  { name: "Iron Man", rating: 4 },
  { name: "Black Panther", rating: 4 },
  { name: "Doctor Strange", rating: 3 },
  { name: "Spider-Man: No Way Home", rating: 5 },
  { name: "Guardians of the Galaxy", rating: 4 },
  { name: "Captain America: The Winter Soldier", rating: 4 },
  { name: "Thor: Ragnarok", rating: 4 },
  { name: "The Avengers", rating: 5 },
  { name: "Ant-Man", rating: 3 },
  { name: "Deadpool", rating: 4 },
  { name: "Logan", rating: 5 },
  { name: "X-Men: Days of Future Past", rating: 4 },
  { name: "Man of Steel", rating: 3 },
  { name: "Wonder Woman", rating: 4 },
  { name: "Aquaman", rating: 3 },
  { name: "Justice League", rating: 2 },
  { name: "The Batman", rating: 5 },
  { name: "Joker", rating: 5 },
  { name: "Suicide Squad", rating: 2 },
  { name: "Shazam!", rating: 3 },
  { name: "The Flash", rating: 3 },
  { name: "The Hunger Games", rating: 4 },
  { name: "Catching Fire", rating: 4 },
  { name: "Mockingjay Part 1", rating: 3 },
  { name: "Mockingjay Part 2", rating: 3 },
  { name: "Twilight", rating: 2 },
  { name: "New Moon", rating: 2 },
  { name: "Eclipse", rating: 2 },
  { name: "Breaking Dawn Part 1", rating: 2 },
  { name: "Breaking Dawn Part 2", rating: 2 },
  { name: "Harry Potter and the Sorcerer's Stone", rating: 5 },
  { name: "Harry Potter and the Chamber of Secrets", rating: 4 },
  { name: "Harry Potter and the Prisoner of Azkaban", rating: 5 },
  { name: "Harry Potter and the Goblet of Fire", rating: 4 },
  { name: "Harry Potter and the Order of the Phoenix", rating: 4 },
  { name: "Harry Potter and the Half-Blood Prince", rating: 4 },
  { name: "Harry Potter and the Deathly Hallows Part 1", rating: 4 },
  { name: "Harry Potter and the Deathly Hallows Part 2", rating: 5 },
  { name: "Fantastic Beasts and Where to Find Them", rating: 3 },
  { name: "Fantastic Beasts: The Crimes of Grindelwald", rating: 2 },
  { name: "Fantastic Beasts: The Secrets of Dumbledore", rating: 3 },
  { name: "The Lion King", rating: 5 },
  { name: "Aladdin", rating: 4 },
  { name: "Beauty and the Beast", rating: 5 },
  { name: "Frozen", rating: 4 },
  { name: "Moana", rating: 4 },
  { name: "Encanto", rating: 4 },
  { name: "Zootopia", rating: 4 },
  { name: "Big Hero 6", rating: 4 },
  { name: "Wreck-It Ralph", rating: 4 },
  { name: "Ralph Breaks the Internet", rating: 3 },
  { name: "Toy Story", rating: 5 },
  { name: "Toy Story 2", rating: 5 },
  { name: "Toy Story 3", rating: 5 },
  { name: "Toy Story 4", rating: 4 },
  { name: "Finding Nemo", rating: 5 },
  { name: "Finding Dory", rating: 4 },
  { name: "Monsters, Inc.", rating: 5 },
  { name: "Monsters University", rating: 4 },
  { name: "Cars", rating: 3 },
  { name: "Cars 2", rating: 2 },
  { name: "Cars 3", rating: 3 },
  { name: "Up", rating: 5 },
  { name: "Inside Out", rating: 5 },
  { name: "Coco", rating: 5 },
  { name: "Soul", rating: 4 },
  { name: "Luca", rating: 4 },
  { name: "Elemental", rating: 3 },
  { name: "The Incredibles", rating: 5 },
  { name: "The Incredibles 2", rating: 4 },
  { name: "Ratatouille", rating: 5 },
  { name: "Wall-E", rating: 5 },
  { name: "A Bug's Life", rating: 4 },
  { name: "Shrek", rating: 5 },
  { name: "Shrek 2", rating: 5 },
  { name: "Shrek the Third", rating: 3 },
  { name: "Shrek Forever After", rating: 3 },
  { name: "Madagascar", rating: 4 },
  { name: "Madagascar: Escape 2 Africa", rating: 4 },
  { name: "Madagascar 3: Europe's Most Wanted", rating: 4 },
  { name: "Kung Fu Panda", rating: 5 },
  { name: "Kung Fu Panda 2", rating: 4 },
  { name: "Kung Fu Panda 3", rating: 4 },
  { name: "How to Train Your Dragon", rating: 5 },
  { name: "How to Train Your Dragon 2", rating: 4 },
  { name: "How to Train Your Dragon: The Hidden World", rating: 4 },
  { name: "Despicable Me", rating: 4 },
  { name: "Despicable Me 2", rating: 4 },
  { name: "Despicable Me 3", rating: 3 },
  { name: "Minions", rating: 3 },
  { name: "Minions: The Rise of Gru", rating: 3 },
  { name: "Ice Age", rating: 4 },
  { name: "Ice Age: The Meltdown", rating: 3 },
  { name: "Ice Age: Dawn of the Dinosaurs", rating: 3 },
  { name: "Ice Age: Continental Drift", rating: 2 },
  { name: "Ice Age: Collision Course", rating: 2 },
  { name: "The Croods", rating: 4 },
  { name: "The Croods: A New Age", rating: 3 },
  { name: "Sing", rating: 4 },
  { name: "Sing 2", rating: 4 },
  { name: "The Secret Life of Pets", rating: 3 },
  { name: "The Secret Life of Pets 2", rating: 3 },
  { name: "Trolls", rating: 3 },
  { name: "Trolls World Tour", rating: 3 },
  { name: "Megamind", rating: 4 },
  { name: "The Boss Baby", rating: 3 },
  { name: "The Boss Baby: Family Business", rating: 2 },
  { name: "Hotel Transylvania", rating: 4 },
  { name: "Hotel Transylvania 2", rating: 3 },
*/
  ];